### ISSUE TITLE
Error starting a node: canvas --dev --tmp

### ISSUE THREAD

**Issue by alixeb** [paritytech/canvas-node#70]
1. Install dependencies with: `cargo install canvas-node --git https://github.com/paritytech/canvas-node.git --force --locked`. It fails without using `--locked`.

2. Run `canvas --dev --tmp`

3. Get some errors in the terminal saying it is a bug and to create an issue

```
2021-08-14 14:07:03 Running in --dev mode, RPC CORS has been disabled.    
2021-08-14 14:07:03 Canvas Node    
2021-08-14 14:07:03 ✌️  version 0.1.0-42252ba-x86_64-macos    
2021-08-14 14:07:03 ❤️  by Canvas, 2020-2021    
2021-08-14 14:07:03 📋 Chain specification: Development    
2021-08-14 14:07:03 🏷 Node name: spotted-ring-7868    
2021-08-14 14:07:03 👤 Role: AUTHORITY    
2021-08-14 14:07:03 💾 Database: RocksDb at /var/folders/qf/31y_8fmd0ybc168g4kqkklw40000gn/T/substrateoPNlI2/chains/dev/db    
2021-08-14 14:07:03 ⛓  Native runtime: canvas-12 (canvas-0.tx1.au1)    
2021-08-14 14:07:03 🔨 Initializing Genesis block/state (state: 0xc64e…6c67, header-hash: 0xf67b…7bc0)    
2021-08-14 14:07:03 👴 Loading GRANDPA authority set from genesis on what appears to be first startup.    
2021-08-14 14:07:03 ⏱  Loaded block-time = 6s from block 0xf67bd5d8dfbfcc3ef1d57ac5ed74f1c918a1145a36ced46f25d862eaddec7bc0    
2021-08-14 14:07:03 Using default protocol ID "sup" because none is configured in the chain specs    
2021-08-14 14:07:03 🏷 Local node identity is: 12D3KooWQgVboU7PT7z7FMdsw8gXYkR4SGjsoQswpWiPNp2suxez    
2021-08-14 14:07:03 could not parse an IP from hosts file    

====================

Version: 0.1.0-42252ba-x86_64-macos

   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: sp_panic_handler::set::{{closure}}
   3: std::panicking::rust_panic_with_hook
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:626:17
   4: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:519:13
   5: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:141:18
   6: rust_begin_unwind
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
   7: core::panicking::panic_fmt
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
   8: core::result::unwrap_failed
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/result.rs:1355:5
   9: hyper_rustls::connector::HttpsConnector<hyper::client::connect::http::HttpConnector>::new
  10: sc_offchain::api::http::SharedClient::new
  11: sc_offchain::OffchainWorkers<Client,Block>::new
  12: sc_service::builder::build_offchain_workers
  13: canvas::command::run::{{closure}}::{{closure}}
  14: tokio::runtime::enter::Enter::block_on
  15: tokio::runtime::context::enter
  16: sc_cli::runner::Runner<C>::run_node_until_exit
  17: canvas::command::run
  18: canvas::main
  19: std::sys_common::backtrace::__rust_begin_short_backtrace
  20: std::rt::lang_start::{{closure}}
  21: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:259:13
      std::panicking::try::do_call
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:401:40
      std::panicking::try
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:365:19
      std::panic::catch_unwind
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:434:14
      std::rt::lang_start_internal
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/rt.rs:34:21
  22: _main


Thread 'main' panicked at 'cannot access native cert store: Custom { kind: Other, error: Error { code: -25262, message: "The Trust Settings Record was corrupted." } }', /Users/alixe/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-rustls-0.21.0/src/connector.rs:46
```  

Any suggestions to troubleshoot and fix?

Thanks

**Comment by HCastano** [comment]
> It fails without using --locked.

This is because we follow the Substrate `master` branch, so when you build without `--locked` it'll pull in the latest Substrate code which usually includes breaking changes. With the `--locked` flag it'll use the `Cargo.lock` file which is a "known good".

As for the error, it looks like it comes from `hyper-rustls-0.21.0`, not `canvas-node` itself. We bumped `hyper-rustls` in https://github.com/paritytech/canvas-node/pull/71, can you try building with that PR (or waiting until it hits `master`) to see if your issue gets resolved?

If it doesn't, I'd recommend opening an issue in the [`hyper-rustls` repo](https://github.com/rustls/hyper-rustls).
